### ISSUE TITLE
WmbMonitor.java with WMBMonitor class

### ISSUE THREAD

**Issue by michaelenglert** [Appdynamics/ibm-websphere-msg-broker-monitor#2]
build error when running mvn clean install

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project ibm-websphere-msg-broker-extension: Compilation failure
[ERROR] /home/michi/workspace/ibm-websphere-msg-broker-monitor/src/main/java/com/appdynamics/extensions/wmb/WmbMonitor.java:[16,7] error: class WMBMonitor is public, should be declared in a file named WMBMonitor.java

Either rename the Java file or the Class accordingly

**Comment by kunalgupApDx** [comment]
Fixed it
